### ISSUE TITLE
About DIML datasets

### ISSUE THREAD

**Issue by puyiwen** [jhornauer/embedded_domain_adaptation#1]
Hi, I download DIML datasets, but I dont find the **"calib color 2-digits.mat"** which intrinsic parameter for color camera. Do you know why? Thank you very much!

**Comment by jhornauer** [comment]
Hi, to run the code in this repository, only the indoor sample images are needed. Therefore, no intrinsic calibration parameters are required. If you have any questions about the dataset, you should contact the publishers of the dataset.
